services:
  web:
    # use nginx as the base docker image for the container
    # this can be an arbitrary image that will be pulled from hub.docker.com
    image: nginx
    # Mount dir in the docker home dir on the host in the container
    volumes:
      - "/home/docker/public:/usr/share/nginx/html/index.html"
    # Expose port 80 in the container as port 80 on the host system
    ports:
      - 80:80
    # Use this line for debugging, to make the container do nothing.
    # We can then run a shell in the container using `docker-compose exec web bash`
    # command: ["sleep", "infinity"]
    security_opt:
      # disable apparmor
      - apparmor:unconfined
